### ISSUE TITLE
Release Candidate v1.0.0 - Broken parsing of MBMS Service Announcement

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-mbms-mw-android#9]
## Description
In the release candidate v1.0.0 (https://github.com/5G-MAG/rt-mbms-mw-android/releases/tag/rt-mbms-mw-android-1.0.0) the parsing of the MBMS Service Announcement file (`bootstrap.multipart.hls`) seems to be broken.

The code stack is the same as the one that was used for the demo at the Media Web Symposium. At this point it is not clear what is causing the issue as the code did not change between the successful demo and the release candidate. 

While investigating the issue, it seems like the callback functions of the `MultipartReader` class are not executed. As a consequence, the function `parse_bootstrap()` is iterating over an empty list of `_items` and is not adding any services. Finally, the playback does not start, although files are received successfully via the rt-mbms-tx-for-qrd-and-crd transmitter.

It would be good to know if this is an issue on my platform and if anyone successfully ran the end to end setup following the tutorial I provided some weeks ago: https://5g-mag.github.io/Getting-Started/pages/lte-based-5g-broadcast/tutorials/android-mw-seamless-switching.html

**Comment by dsilhavy** [comment]
@jordijoangimenez Fyi, let's discuss in the call tomorrow. At this point I am not sure what is happening it would be good if someone can confirm that the issue exists outside my development setup.

**Comment by hmmanish** [comment]
I was trying to setup the project based on tutorial and faced this parsing issue related _bootstrap.multipart.hls_,

 Issue seems to be associated with EOL in _bootstrap.multipart.hls_ file.

As a solution I opened up _bootstrap.multipart.hls_ in notepad++ converted end of line to CRLF. It worked!!. 
This has resolved the parsing issue and we could see __items_ getting populated.

Further we can see broadcast packets are being received inside middleware transmitted from receiver.

We can also see segments are being added to middle ware cache and all TOIs being received. 

But we are blocked at the point where we couldn';t see any call being made to the function **void _MBMS_RT::RestHandler::get(http_request message)_** and this is not getting fire up. I guess once we this is triggered App can play the stream.

Currently we are debugging this issue and have not found the solution that from where it is triggered. it would be good if you can provide some input regarding the same. @dsilhavy 


> @jordijoangimenez Fyi, let's discuss in the call tomorrow. At this point I am not sure what is happening it would be good if someone can confirm that the issue exists outside my development setup.

**Comment by dsilhavy** [comment]
Thanks @hmmanish that is a good observation. I can confirm that the parsing issue was related to the line seperator format. Changing to `CRLF` solves the problem.

Note that this can be done directly in Android Studio on the bottom right:

<img width="569" alt="Bildschirmfoto 2024-08-02 um 10 20 09" src="https://github.com/user-attachments/assets/7553b481-578e-4194-ab99-a14b34e09fa5">

Can you please further elaborate on your setup. Which transmitter are you using? Are you connected to a Wifi network as well and adjusted the IPs in the SA as documented in the end to end setup: https://5g-mag.github.io/Getting-Started/pages/lte-based-5g-broadcast/tutorials/android-mw-seamless-switching.html

**Comment by dsilhavy** [comment]
Changed default line separator format to `CRLF` here: https://github.com/5G-MAG/rt-mbms-mw-android/commit/03a4a630f51fc72474d4dc39a9be3d17ade45b0e

**Comment by hmmanish** [comment]
Thanks for your reply @dsilhavy. Our setup is on Wifi and we have adjusted the IP in _bootstrap.multipart.hls_ 

Here is the detail about setup: 

1. We are not using Modem or any hardware(bladerf). i.e. there is no SDR and neither _rt-mbms-tx-for-qrd-and-crd_
2. We start flute transmitter on Ubuntu going through the pat _rt-mbms-examples/flute-ffmpeg/build_
3. We have configured flute-ffmpeg config 

general : {
          multicast_ip = "239.11.4.50";
          multicast_port = 9988;
          mtu = 1500;
          rate_limit = 1200000;
          watchfolder_path = "/android/rt-mbms-examples/simple-express-server/public/watchfolder/hls";
          path_to_transmit = "/var/www/watchfolder/hls/"
....}

4. We start hls transmission from _rt-mbms-examples/flute-ffmpeg/files_ and have configured stream params
5. We could see TOI being received by flute receiver on Ubuntu. This is just to verify that flute transmitter and receiver are in sync on Ubuntu
6. We have also started local server on Ubuntu and could play the manifest.m3u8 geenrated in HLS browser

Further on Android middleware side we did some changes to run on Android 

1. We have commented out following code to bypass MbmsGroupCallSession as we are interested only on interface name
```
//        if (!connectingToMiddleware) {
//            connectingToMiddleware = true
//            Log.i(TAG, "Connecting to middleware in RTP mode")
//            executorService.execute {
//                groupCallSession =
//                    MbmsGroupCallSession.create(
//                        applicationContext,
//                        executorService,
//                        groupCallSessionCallback
//                    )
//            }
//        }
```
2. Instead, we have following line of code gets executed when we connect to middleware is pressed. we get interface name through some other Android utility methods

```
    fun connectToMiddleware() {

        udpReceiver = UdpReceiver(applicationContext, "wlan0")
        receiveThread = Thread(udpReceiver)
        receiveThread!!.start()
}
```
3. Hence, we are not replying on Android MBMS group session callbacks.  that means following code are bypassed

_groupCall = groupCallSession?.startGroupCall(
                        tmgi,
                        listOf(0), listOf(0), executorService, groupCallCallback
                    )_


4. When we start Android MW on device we could packets are getting received and added to FDT and Cache

<img width="863" alt="FileDelivery Table" src="https://github.com/user-attachments/assets/fcb0cb27-4864-407e-a2c5-e3ab34a16364">


![Screenshot 2024-07-29 175827](https://github.com/user-attachments/assets/2b4a23ed-f733-4d2e-b3a7-c4b708725ee9)

5. Further we are not seeing stream is getting played out with broadcast segments received. 

Note we are also not running Android Media session handler https://github.com/orgs/5G-MAG/repositories?q=session

I am not sure what I am missing here as **MBMS_RT::RestHandler::get(http_request message) is not triggered** in this setup. 





> Thanks @hmmanish that is a good observation. I can confirm that the parsing issue was related to the line seperator format. Changing to `CRLF` solves the problem.
> 
> Note that this can be done directly in Android Studio on the bottom right:
> 
> <img alt="Bildschirmfoto 2024-08-02 um 10 20 09" width="569" src="https://private-user-images.githubusercontent.com/2427039/354524005-7553b481-578e-4194-ab99-a14b34e09fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDIyMzAsIm5iZiI6MTcyMjcwMTkzMCwicGF0aCI6Ii8yNDI3MDM5LzM1NDUyNDAwNS03NTUzYjQ4MS01NzhlLTQxOTQtYWI5OS1hMTRiMzRlMDlmYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTYxODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RmMGE3ODU2OTU5YTllOGJmYjVhYmQ3OTVmNTAzNmFkYmU3NTBlOTY2NzUyYWExYjQ1MjRlNzM1NjcyMGExNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gArGMY5TkkkMbGvNpzepBUWIt1SpyQna_DdXY0dsvQY">
> Can you please further elaborate on your setup. Which transmitter are you using? Are you connected to a Wifi network as well and adjusted the IPs in the SA as documented in the end to end setup: https://5g-mag.github.io/Getting-Started/pages/lte-based-5g-broadcast/tutorials/android-mw-seamless-switching.html

**Comment by dsilhavy** [comment]
Thanks for the detailed description @hmmanish . A few comments:

* The MediaSessionHandler is required for the setup of the 5G Media Streaming Stack. For our 5G Broadcast setup, you don't need it. 
* Is `MBMS_RT::RestHandler::get` not triggered at all? Did you set a breakpoint at the entry line of the function? In my first tests, the files were saved with a slightly different name than the name that was used for the request. This was leading to cache misses but the function was called.
* Do you see any logs in Android Studio Logcat indicating which files the Android MW is requesting once you hit the play button?
* If you can provide a link to your changes (probably on a fork?) I might be able to have a look in the next weeks.

**Comment by hmmanish** [comment]
> Thanks for the detailed description @hmmanish . A few comments:
> 
> * The MediaSessionHandler is required for the setup of the 5G Media Streaming Stack. For our 5G Broadcast setup, you don't need it.
> * Is `MBMS_RT::RestHandler::get` not triggered at all? Did you set a breakpoint at the entry line of the function? In my first tests, the files were saved with a slightly different name than the name that was used for the request. This was leading to cache misses but the function was called.
> * Do you see any logs in Android Studio Logcat indicating which files the Android MW is requesting once you hit the play button?
> * If you can provide a link to your changes (probably on a fork?) I might be able to have a look in the next weeks.

Thanks @dsilhavy . After further debugging the issue I found that our path to transmit configured was the main issue. due to which content location for FDT entries was not matching with expected value. after doing some hacking - removing unwanted leading values from content location. we can see media is playing out both from 5GBC and CDN.

**Comment by dsilhavy** [comment]
Thanks for updating us @hmmanish . As the original issue was solved, I am closing this. See also https://github.com/5G-MAG/rt-mbms-mw-android/commit/03a4a630f51fc72474d4dc39a9be3d17ade45b0e
